-- CREATE SEQUENCE IF NOT EXISTS client_number_seq START 100000 INCREMENT 1;
--
-- CREATE OR REPLACE FUNCTION generate_client_number()
--     RETURNS TRIGGER AS $$
-- DECLARE
--     next_client_number INTEGER;
-- BEGIN
--     LOOP
--         next_client_number := floor(random() * 900000 + 100000);
--         EXIT WHEN NOT EXISTS (
--             SELECT 1 FROM users WHERE client_number = next_client_number
--         );
--     END LOOP;
--
--     NEW.client_number := next_client_number;
--     RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;
--
-- CREATE TRIGGER set_client_number
--     BEFORE INSERT ON users
--     FOR EACH ROW
--     WHEN (NEW.client_number IS NULL)
-- EXECUTE FUNCTION generate_client_number();